### ISSUE TITLE
Download unavailable

### ISSUE THREAD

**Issue by aroeiraio** [patrickelectric/qhot#15]
Hello Patrick,

I would like to test qhot, but download for Linux is unavailable. Could you check?

Best regards

**Comment by cassianorabelo** [comment]
Actually the download is no longer available for any platform... Windows user here.

**Comment by patrickelectric** [comment]
Sorry for that!
They should be available again now

**Comment by patrickelectric** [comment]
Sadly, linux is still a problem, I'll try to fix that during the week.

**Comment by patrickelectric** [comment]
Everything should be fixed by now
