### ISSUE TITLE
segfault when using QtCharts

### ISSUE THREAD

**Issue by joaoantoniocardoso** [patrickelectric/qhot#19]
Hi!

I was running `qhot main.qml` in my project and everything was going fine until I started to work with `QtCharts 2.3`:
``` Zsh
> qhot main.qml        
qrc:/main.qml:104:5: QML Connections: Implicitly defined onFoo properties in Connections are deprecated. Use this syntax instead: function onFoo(<arguments>) { ... }
[1]    537113 segmentation fault (core dumped)  qhot main.qml
```

Here is a minimal code example to reproduce the bug:
```QML
import QtQuick 2.15
import QtCharts 2.3

Rectangle {
    color: "red"
    ChartView { }
}
```
Then it runs if I comment out `ChartView { }`.

Besides that, I can normally run my application binary.

I am using Arch Linux (updated) with the current qt5 package group.

Thanks!

**Comment by emimvi** [comment]
Also hit this issues, both in qhot and my own app. Seems like QtCharts uses QWidgets internally, and thus needs a full `QApplication` instead of `QGuiApplication`. Patching qhot to use `QApplication` and requiring the Widgets component in the CMakeLists works for me.

**Comment by joaoantoniocardoso** [comment]
> Also hit this issues, both in qhot and my own app. Seems like QtCharts uses QWidgets internally, and thus needs a full `QApplication` instead of `QGuiApplication`. Patching qhot to use `QApplication` and requiring the Widgets component in the CMakeLists works for me.

Could you make a draft/PR with those changes?

**Comment by emimvi** [comment]
@joaoantoniocardoso Not sure if you got a notification for it, but I added a PR.
