### ISSUE TITLE
The console doesn't print message 

### ISSUE THREAD

**Issue by happydpc** [patrickelectric/qhot#2]
On windows, the cmd window doesn't print the output message. 
![微信图片_20191019093109](https://user-images.githubusercontent.com/771776/67136027-3b250500-f253-11e9-853d-573dcfdc6815.png)

**Comment by patrickelectric** [comment]
Hi @happydpc! Sorry for missing your issue, I'll take a look asap.

**Comment by patrickelectric** [comment]
Can you test this release: https://github.com/patrickelectric/qhot/releases/download/continuous/qhot_release.zip ?

**Comment by patrickelectric** [comment]
The last version is working, just did the test here
